### ISSUE TITLE
%IW Problems 

### ISSUE THREAD

**Issue by KonradMWM** [CONTROLLINO-PLC/OpenPLC_examples#1]
I get CONTROLLINO pinout definitions for your publication. When i add% IW0 &% IW1 as bool - its dont work correctly.
Additional information is needed that% IW0 [A0] and% IW1 [A1] can only be set as INT, to use bool we have to use INT-> Bool converter and Bool auxiliary variable.

**Comment by LukasSeget** [comment]
Hello Konrad, I am sorry, but I do not understand your problem. May I ask you to share a source code, please? Thanks, Lukas

**Comment by pmmarquez** [comment]
> I get CONTROLLINO pinout definitions for your publication. When i add% IW0 &% IW1 as bool - its dont work correctly. Additional information is needed that% IW0 [A0] and% IW1 [A1] can only be set as INT, to use bool we have to use INT-> Bool converter and Bool auxiliary variable.

Hello Konrad sorry for the late reply, as in the variable name "W"(IW0) you need to define them as WORD in order for the program to work correctly, in the current version of OpenPLC Editor for Arduino the I/Os definition is fixed so you should use them [like explained](https://github.com/CONTROLLINO-PLC/OpenPLC_examples#controllino-pinout-definitions-for-openplc-integration), any way if you need some more specific I/O definition write to techsupport@controllino.com and we will try to help you 👍🏽
